/** De onde cada stat de conquista ou pedido é incrementado. */

export const STAT_SOURCES: Record<string, { where: string }> = {
  missionsDone: { where: 'firestoreService.completeTaskWithRewards' },
  morningEarly: { where: 'firestoreService.completeTaskWithRewards' },
  recoveries: { where: 'firestoreService.completeTaskWithRewards (late)' },
  fullDaysCount: { where: 'dailyRulesService.closeDay' },
  fullDaysBest: { where: 'dailyRulesService.closeDay' },
  perfectWeeks: { where: 'dailyRulesService.closeDay' },
  noPunishDays: { where: 'dailyRulesService.closeDay' },
  quizStreak: { where: 'dailyQuizService.completeDailyQuiz' },
  reflections: { where: 'dailyQuizService.completeDailyQuiz' },
  quizzesDone: { where: 'dailyQuizService.completeDailyQuiz' },
  quizScore: { where: 'dailyQuizService.completeDailyQuiz' },
  quizPerfect: { where: 'dailyQuizService.completeDailyQuiz' },
  booksRead: { where: 'bookService.payBookReport' },
  contractsLetter: { where: 'englishBaseService.completeContract' },
  contractsNote: { where: 'englishBaseService.completeContract' },
  contractsForge: { where: 'englishBaseService.completeContract' },
  contractsMerchant: { where: 'englishBaseService.completeContract' },
  contractsPerfect: { where: 'englishBaseService.completeContract' },
  contractsWeek: { where: 'englishBaseService.completeContract' },
  contractsDone: { where: 'englishBaseService.completeContract' },
  themesSet: { where: 'englishBaseService.setThemeRequest' },
  wordsMastered: { where: 'englishBaseService.completeContract (vocab.seen >= 3)' },
  smelts: { where: 'villageService.tradeMaterials' },
  burns: { where: 'villageService.burnWood' },
  streakChests: { where: 'villageService.openStreakChest' },
  emeraldsEver: { where: 'villageService.grantRare / openDailyChest' },
  diamondsEver: { where: 'villageService.grantRare / openStreakChest' },
  talksSameDay: { where: 'villageService.talkToNpc' },
  nightComplete: { where: 'villageService.completeNight' },
  merchantSales: { where: 'villageService.sellMaterials (pedra, quantidade need)' },
  goalsAchieved: { where: 'goalsService.finishGoal' },
  bigGoals: { where: 'goalsService.finishGoal (settings/economy incomeDayGold * 20)' },
  interestWeeks: { where: 'goalsService.applyWeeklyInterest' },
  challengesDone: { where: 'challengesService.completeChallenge' },
  agendaPlanned: { where: 'agendaService.createAgendaItem' },
  organizedWeeks: { where: 'agendaService.weeklyOrganizedBonus' },
  focusBlocks: { where: 'agendaService.finishFocusBlock' },
  agendaDone: { where: 'agendaService.markAgendaDone' },
  redstoneDone: { where: 'redstoneService.completeRedstone' },
  redstonePerfect: { where: 'redstoneService.completeRedstone' },
  redstoneStages: { where: 'redstoneService.completeRedstone' },
  shopBuys: { where: 'villageService.buyCosmetic' },
  craftsDone: { where: 'villageService.craftGear' },
  tradesDone: { where: 'villageService.tradeMaterials' },
  chestsOpened: { where: 'villageService.openDailyChest' },
  buildsDone: { where: 'englishBaseService.buildUpgrade' },
  deposits: { where: 'goalsService.depositGoal' },
  savedGold: { where: 'goalsService.depositGoal' },
  plansSaved: { where: 'villageService.savePlan' },
  checkins: { where: 'villageService.submitCheckin' },
  npcTalks: { where: 'villageService.talkToNpc' },
  level: { where: 'progress.totalXP via getLevelFromXP' },
  'building:fornalha': { where: 'englishBase.buildings (evaluateAchievements)' },
  buildingsMin: { where: 'englishBase.buildings (evaluateAchievements)' },
  pickaxe: { where: 'village.gear (evaluateAchievements)' },
  helmet: { where: 'village.gear (evaluateAchievements)' },
  gearAll: { where: 'village.gear (evaluateAchievements)' },
  'npcTier:comerciante': { where: 'village.npcs (evaluateAchievements)' },
  'npcTier:sabio': { where: 'village.npcs (evaluateAchievements)' },
  'npcTier:ferreiro': { where: 'village.npcs (evaluateAchievements)' },
  'npcTier:olheiro': { where: 'village.npcs (evaluateAchievements)' },
  npcTiersMin: { where: 'village.npcs (evaluateAchievements)' },
  milestonesOwned: { where: 'village.owned (evaluateAchievements)' },
  seasonsDone: { where: 'villageService.closeSeason' },
};
